### ISSUE TITLE
Error during ESP Info request on macOs 12

### ISSUE THREAD

**Issue by hredan** [hredan/ESPEASYFLASHER_2.0#29]
OS: macOs12
ESP Info request

Exception in thread Thread-1 (esptool_esp_info):
Traceback (most recent call last):
  File "threading.py", line 1073, in _bootstrap_inner
  File "threading.py", line 1010, in run
  File "eef_modules/eef_esptool_com/esptool_com.py", line 82, in esptool_esp_info
  File "eef_modules/eef_esptool_com/esptool_com.py", line 93, in run_esptool
FileNotFoundError: [Errno 2] No such file or directory: './ESP_Packages'

**Comment by hredan** [comment]
could be solved by using [tempfile](https://docs.python.org/3/library/tempfile.html)
